name: OZIP Decrypter by TechyMinati... & Tweaked by sauraj

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://fsopen.coloros.com/3/oppowww/androidrom/r11/R11_11_OTA_0530_all_jfW5v0iZuYpa.ozip #edit link here...
  FIRMWARE_NAME: R11_11_OTA_0530_all_jfW5v0iZuYpa.ozip  #edit file name here, you can find the name of file from link itself...
  FINAL_ZIP_NAME: R11.zip #This will be the name of final zip which will be uploaded. You can leave it unchanged.
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python-pip
             sudo -H pip install --upgrade pip
             sudo -H pip install setuptools wheel docopt pycryptodome
             wget https://raw.githubusercontent.com/techyminati/oppo_ozip_decrypt/master/ozipdecrypt.py
             sudo python ozipdecrypt.py $FIRMWARE_NAME

       - name: ziping decrypted file
         run: |
             cd out
             sudo zip -r $FINAL_ZIP_NAME * #Don't edit it. Don't edit it and Don't edit this line.

       - name: Upload Decrypted zip
         run: |
             cd out
             curl --upload-file ./$FINAL_ZIP_NAME https://transfer.sh/$FINAL_ZIP_NAME https://transfer.sh/66nb8/$FINAL_ZIP_NAME  #file will be uploaded to bashupload, so mirror it if you are decrypting for community uses.
